# Generated by Django 5.2 on 2026-04-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('', 'Select Category'), ('technology', 'Technology'), ('lifestyle', 'Lifestyle'), ('coding', 'Coding')], max_length=25),
        ),
    ]
